### ISSUE TITLE
Adding "advancedPHP" to your Theme

### ISSUE THREAD

**Issue by dennisosaj** [roofdog/roofdog.Monokle#1]
Heyho,
I saw your theme and noticed a growing popularity.

I'm asking if you could add "advancedPHP" to your theme. It's one of my own extensions and I want to provide more theme coverage for my users.

You can find a theme development documentation in its repo: https://github.com/dennisosaj/advancedphp.novaextension

I would really appreciate it. Thanks!

**Comment by roofdog** [comment]
Hi @dennisosaj 

Thanks for getting in touch. To be honest the initial release was done pretty quickly to satisfy my own needs and there are a few issues that need addressing so I will be looking to do an update soon.

I already plan on adding support for advancedPHP in the future so I'll look to add it in the next release.

Cheers
